package comp3111.covid;


import javafx.fxml.FXML;
import javafx.collections.ObservableList;
import javafx.scene.chart.CategoryAxis;
import javafx.scene.chart.LineChart;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.XYChart;
import javafx.scene.control.TextArea;

/**
 * Building on the sample skeleton for 'ChartB2.fxml' Controller Class generated by SceneBuilder
 */

public class ChartB2Controller{
	
	@FXML
    private LineChart<String, Double> ChartB2;
	
    @FXML
    private CategoryAxis xAxis;

    @FXML
    private NumberAxis yAxis;
    
    @FXML
    private TextArea textAreaConsole;
		
	
	/**
	 * 
	 * @param series The ObservableList containing the data points to be shown in the chart
	 * @param text The text message shown in the Text Area Console
	 */

    public void showChart(ObservableList<XYChart.Series<String, Double>> series, String text) {
		
		ChartB2.getData().addAll(series);
		
        textAreaConsole.setText(text);
        textAreaConsole.setEditable(false);
		
	}
}
