package comp3111.covid;

import java.net.URL;
import java.util.ResourceBundle;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.chart.LineChart;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.XYChart;

/**
 * Building on the sample skeleton for 'ComDeatureA.fxml' Controller Class generated by SceneBuilder
 *
 */
public class ComFeatureAController implements Initializable{
	ComFeatureA data;
	int dataPoint;
	
    @FXML
    private LineChart<Double, Double> ComFeatureA;

    @FXML
    private NumberAxis xAxis;

    @FXML
    private NumberAxis yAxis;
    
    /**
     * 
     * @param data The ComFeatureA instance
     * @param dataPoint Number of data point to plot
     */
    public ComFeatureAController(ComFeatureA data, int dataPoint) {
		this.data = data;
		this.dataPoint = dataPoint;
	}
    
    /**
     * Initialize the scene
     */
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		// input the data into the chart
		XYChart.Series<Double, Double> series = new XYChart.Series<Double, Double>();
        series.setName("Tengency of the date between different country");
        for(XYChart.Data<Double, Double> datapoint: data.data) {
        	series.getData().add(datapoint);
        }
        ComFeatureA.getData().add(series);
        //ComFeatureA = new LineChart<Number, Number>(xAxis, yAxis);

		// set y axis
        yAxis.setAutoRanging(false);
        yAxis.setUpperBound(data.maxConfirmedPercentage+0.5);
        yAxis.setTickUnit((data.maxConfirmedPercentage+0.5)/5);
        yAxis.setLabel("Percentage of total confirmed cases / population");
        
        // set x axis
        xAxis.setAutoRanging(false);
        xAxis.setUpperBound(data.maxTestPercentage);
        xAxis.setTickUnit(data.maxTestPercentage/5);
        xAxis.setLabel("Percentage of total test / population");
	}

}