package comp3111.covid;

import javafx.fxml.FXML;
import javafx.collections.ObservableList;
import javafx.scene.chart.ScatterChart;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.XYChart;
import javafx.scene.control.TextArea;
import javafx.scene.control.Label;

/**
 * Building on the sample skeleton for 'FeatureB.fxml' Controller Class generated by SceneBuilder
 */

public class ComFeatureBController{
	
    @FXML
    private NumberAxis xAxis;

    @FXML
    private NumberAxis yAxis;
    
	@FXML
    private ScatterChart<Number, Number> FeatureB;
    
    @FXML
    private TextArea textAreaConsole;
    
    @FXML
    private Label titleB;
		
	
	/**
	 * 
	 * @param series The ObservableList containing the data points to be shown in the chart
	 * @param text The text message to be shown in Text Area Console
	 * @param attribute The attribute interested
	 */

    public void showChart(ObservableList<XYChart.Series<Number, Number>> series, String text, String attribute) {
		
		FeatureB.getData().addAll(series);
		
        textAreaConsole.setText(text);
        textAreaConsole.setEditable(false);
        
        titleB.setText("Relation between confirmed deaths and " + attribute);
		
	}
}
